compressionLevel: 9

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
    - ia64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - win32
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.1.cjs
